### ISSUE TITLE
non-physical observe action passed validating

### ISSUE THREAD

**Issue by BenCooke95** [rockit-astro/opsd#14]
Following action passed ops validation check (despite -2 in start minute)

        {
            "type": "ObserveAltAzField",
            "start": "2022-05-24T05:-2:02Z",
            "end": "2022-05-24T05:05:00Z",
            "alt": 28.18863991,
            "az": 125.92516429999999,
            "onsky": true,
            "cam1": {
                "exposure": 0.25
            },
            "cam2": {
                "exposure": 0.25
            },
            "pipeline": {
                "prefix": "44713",
                "type": "SCIENCE",
                "archive": {
                    "CAM1": true,
                    "CAM2": true
                }
            }
        }

**Comment by pchote** [comment]
Fixed by https://github.com/warwick-one-metre/warwick-observatory-common/commit/e41c32aa4dca0a515cc38eb06cfb400413f84c19.
